---
title: "Elevated plasma complement components in facioscapulohumeral dystrophy"
author: "Chao-Jen Wong"
date: "`r Sys.Date()`"
documentclass: "book"
site: bookdown::bookdown_site
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: FredHutch/Wellstone_Plasma_Complement_in_FSHD
description: "analysis workflow and R codes supporting the manuscript - Elevated plasma complement components in facioscapulohumeral dystrophy"
---

# Preface {-}
The purpose of this book is to support the transparency and reproducibilty of the statistical analysis for our manuscript -- _Elevated plasma complement components in facioscapulohumeral dystrophy_. This book contains details of our analysis approaches and automatically executable R codes; the figures and tables on the manuscript were rendered on the fly by running this book's [source Rmd files](https://github.com/FredHutch/Wellstone_Plasma_Complement_in_FSHD/tree/main/gitbook).  This book is built by R markdown, **knitr** [@xie2015], and **bookdown** [@R-bookdown].

For scientific description, we recommend readers to consult the publication (link here). 

## System requirement and software
- R $\geq$ 4.0.3
- The _tidyverse_ project packages
- _BiocStyle_, _Rmarkdown_, _bookdown_, _knitr_, and  _tinytex_ packages

## Samples and datasets
In this repository, we prepared four [datasets](https://github.com/FredHutch/Wellstone_Plasma_Complement_in_FSHD/tree/main/data) for first, second, discovery, and combined cohorts. They are all R `data.frame` instances, with rows presenting samples and columns the complement components.

In our github repos [data](https://github.com/FredHutch/Wellstone_Plasma_Complement_in_FSHD/tree/main/data) folder, we have 

```{r dataset, echo=FALSE}
suppressPackageStartupMessages(library(dplyr))
data.frame(dataset = c("table_1.rda", "table_2.rda", 
                       "table_3.rda", "table_4_update.rda"),
           description=c("first cohort, first visits",
                         "second cohort, first visits",
                         "discovery cohort of selected samples from first and second cohorts",
                         "comprehensive set of first and second cohorts and re-runs and second visit samples")) %>%
  knitr::kable(caption="Description of datasets in the data folder")
```
Note that the discovery cohort is a combined cohort consisted of controls from the second cohort, second visits from the first cohort, and first visits from the second cohort. All these plasma samples were from the same assay date. 


## Methods
We applied the following methods the first, second, and discovery cohorts.

- **$t$-test.** for first and second cohort, we compared FSHDs with controls. Then we examed whether the first and second cohorts give consistent or different signatures.
- **Normalization.** For each complement (column), wevscaled the protein levels by z-score. 
- **Composite score.**  The per-sample composite z-score is the sum of the z-score of all the complement components. 
- **Partial composite score.** For each sample, partial composite score is the sum of selected complement components.
- **Discovery cohort.** The discovery cohort consists of samples from first and second cohorts. We performed pricipal component analysis to classify different groups of FSHDs and identify the components that are better discriminate FSHDs from controls.

### Normalization

__z-score:__ Let $x_{i, j}$ be the values of the matrix $X$, where $i \in \{1, 2, \dots, I\}$ denotes the sample, $j \in \{1, 2, \dots, J\}$ the complement component. For each complement component, $i$, $\overline{X}_j$ denotes the sample mean and $SD_j$ the standard deviation. For each complement $i$ and sample $j$, the normalized score is given by $z_{i, j} = \frac{x_{i, j} - \overline{X}_j}{SD_j}$. The standardized z-score gives the number of standard deviation by which the value is above or below the observed sample means. 